accounts/api/urls.py
from django.urls import path, include

app_name = "accounts"

urlpatterns = [
    path('o/', include('oauth2_provider.urls')),
    path('dashboard/', include('accounts.dashboard.api.urls')),
]

accounts/urls.py
from django.urls import path, include
from accounts import views


app_name = "accounts"


urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login_view"),
    path('signup/', views.SignupView.as_view(), name='signup_view'),
    path('activate/<str:uidb64>/<str:token>/', views.ActivateAccount.as_view(), name='activate-account'),
    path('logout/', views.LogoutView.as_view(), name="logout_view"),
    path('dashboard/', include('accounts.dashboard.urls')),
    path('settings/', views.UpdateSettings.as_view(), name='settings'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit-profile'),
]

api/urls.py
from django.urls import path, include
from django.conf import settings
from api import views

app_name = "api"

urlpatterns = [
    path('accounts/', include('accounts.api.urls')),
    path('pentesting/', include('pentesting.urls')),
    path('status/check', views.CheckStatus.as_view(), name='check-status'),
    path('public/', include('public.api.urls')),
]

if settings.ENABLE_BUGHUNTING_APPLICATION:
    urlpatterns += [
        path('bughunting/', include('bughunting.api.urls')),
    ]

if settings.ENABLE_BLOGGING_APPLICATION:
    urlpatterns += [
        path('blogs/', include('blogging.urls'))
    ]

opas_f_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework.permissions import IsAuthenticated
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Open Pentesting and Security Framework API",
        default_version="v1",
        description="API of the Open Pentesting and Security Framework",
        contact=openapi.Contact(email=settings.DEFAULT_FROM_EMAIL),
        license=openapi.License(name="GPLv3")
    ),
    public=False,
    permission_classes=(IsAuthenticated,),
)


urlpatterns = [
    path('api/', include('api.urls')),
    path('api-docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('accounts/', include('accounts.urls')),
    path('bughunting/', include('bughunting.urls')),
    path('', include('public.urls')),
    path('master-slave/', include('master_slave.urls'))
]


if settings.ENABLE_ADMIN_INTERFACE:
    urlpatterns += [
        path(settings.ADMIN_URL_PATH, admin.site.urls),
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from pentesting import models as pentesting_models


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    about_me = models.TextField(blank=True)
    contact_details = models.TextField(blank=True, null=True)
    email_confirmed = models.BooleanField(default=False)
    public_key = models.TextField(blank=True, null=True)
    prefered_bug_bounty = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.user.username

    @property
    def vulnerability_count(self):
        return self.user.vulnerability_set.count()

    @property
    def host_count(self):
        return pentesting_models.Host.objects.filter(project__userproject__user=self.user).count()

    @property
    def service_count(self):
        return pentesting_models.Service.objects.filter(host__project__userproject__user=self.user).count()

    @property
    def credential_count(self):
        return pentesting_models.Credential.objects.filter(service__host__project__userproject__user=self.user).count()

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"


class AccountSettings(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bughunting_email_submit = models.BooleanField(default=False)
    public_profile = models.BooleanField(default=True)
    # enable_public_mailbox = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Account Settings"
        verbose_name_plural = "Account Settings"


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


def create_account_settings(sender, instance, created, **kwargs):
    if created:
        AccountSettings.objects.create(user=instance)


post_save.connect(create_user_profile, sender=User)
post_save.connect(create_account_settings, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from accounts import models


class SettingsForm(forms.ModelForm):
    class Meta:
        model = models.AccountSettings
        exclude = ['user']


class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput, label="Password (confirm)")

    class Meta:
        model = User
        fields = ['username', 'password', 'password1', 'email']

    def validate_password(self, value):
        password_validation.validate_password(value)
        return value

    def clean(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('password1'):
            raise forms.ValidationError("Passwords do not match!")


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = models.UserProfile
        fields = ['about_me', 'prefered_bug_bounty', 'contact_details']

accounts/dashboard/api/views.py
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from bughunting.models import Bug


class PatchedUnpatchedStatistic(generics.RetrieveAPIView):
    permission_classes = [IsAuthenticated]

    def retrieve(self, request, *args, **kwargs):
        bugs = Bug.objects.filter(bugmeta__approved=True, bugmeta__user=self.request.user)
        patched = bugs.filter(bugmeta__is_fixed=True).count()
        unpatched = bugs.filter(bugmeta__is_fixed=False, bugmeta__is_disclosed=True).count()
        awaiting_response = bugs.filter(bugmeta__is_disclosed=False).count()
        data = {'patched': patched, 'unpatched': unpatched, 'awaiting_response': awaiting_response}
        return Response(data)

accounts/dashboard/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from bughunting.models import Bug


class Dashboard(LoginRequiredMixin, generic.TemplateView):
    template_name = "accounts/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['latest_submissions'] = Bug.objects.filter(bugmeta__user=self.request.user, bugmeta__approved=True)[:5]
        return context

accounts/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.views import generic
from django.contrib import messages
from django.conf import settings
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from accounts import forms
from accounts import models
from accounts.utils import signup
from bughunting.models import Bug


class LoginView(auth_views.LoginView):
    """ login user """
    template_name = 'accounts/login_page.html'
    success_url = reverse_lazy('accounts:dashboard')
    redirect_authenticated_user = True


class LogoutView(auth_views.LogoutView):
    """ logout user """
    pass


class UpdateSettings(LoginRequiredMixin, generic.UpdateView):
    form_class = forms.SettingsForm
    template_name = 'accounts/pages/settings.html'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        return get_object_or_404(queryset)

    def get_queryset(self):
        return models.AccountSettings.objects.filter(user=self.request.user)

    def get_success_url(self):
        return reverse_lazy('accounts:dashboard')


class EditProfileView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'accounts/pages/edit_profile_page.html'
    form_class = forms.EditProfileForm

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        try:
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404('No profile found matching the query')
        return obj

    def get_success_url(self):
        return reverse_lazy('accounts:profile', kwargs={'pk': self.request.user.pk})

    def get_queryset(self):
        return models.UserProfile.objects.filter(user=self.request.user)


class ProfileView(generic.DetailView):
    template_name = 'accounts/pages/profile.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['reported_bugs'] = Bug.objects.filter(bugmeta__user__pk=self.kwargs.get('pk'), bugmeta__approved=True)
        return context

    def get_queryset(self):
        return User.objects.filter(pk=self.kwargs.get('pk'), accountsettings__public_profile=True)


class SignupView(generic.FormView):
    template_name = "accounts/pages/signup.html"
    form_class = forms.SignupForm
    success_url = reverse_lazy('accounts:login_view')

    def get_context_data(self, **kwargs):
        context = super(SignupView, self).get_context_data(**kwargs)
        context['REGISTRATION_ENABLED'] = settings.ENABLE_REGISTRATION
        return context

    def form_valid(self, form):
        if not settings.ENABLE_REGISTRATION:
            # do nothing, signup disabled
            return super(SignupView, self).form_valid(form)
        user = User(username=form.cleaned_data.get('username'))
        user.set_password(form.cleaned_data.get('password'))
        user.save()
        if settings.REQUIRE_SIGNUP_EMAIL_CONFIRM:
            user.is_active = False
            user.email = form.cleaned_data.get('email')
            user.save()
            signup.prepare_signup_email(self.request, user)
        return super(SignupView, self).form_valid(form)


class ActivateAccount(generic.RedirectView):
    url = reverse_lazy('accounts:login_view')

    def get(self, request, *args, **kwargs):
        uidb64 = self.kwargs.get('uidb64')
        token = self.kwargs.get('token')
        result, user = signup.activate_account_check(uidb64, token)
        if result:
            user.is_active = True
            user.save()
            messages.add_message(request, messages.SUCCESS, "Account activated!")
        else:
            messages.add_message(request, messages.ERROR, "Account activation failed!")
        return super(ActivateAccount, self).get(request, *args, **kwargs)

accounts/templates/accounts/pages/edit_profile_page.html
{% extends 'content_container.html' %}

{% block title %}Edit Profile - {% endblock title %}

{% block content %}
    <h3 class="text-center">Edit Profile</h3>
    <hr/>

    <form class="form" method="POST">
        {% csrf_token %}
        {% include 'form.html' %}
        <button class="btn btn-primary float-right">Save</button>
    </form>
{% endblock content %}

accounts/templates/accounts/pages/profile.html
{% extends 'content_container.html' %}


{% block title %}{{ user }} - {% endblock title %}


{% block content %}
    <h3 class="text-center">{{ user }}</h3>
    <hr />
    {% if user == request.user %}
        <a class="float-right btn btn-outline-info" href="{% url 'accounts:edit-profile' %}"><i class="fa fa-edit"></i> Edit</a>
    {% endif %}
    {% if user.first_name or user.last_name %}
        <p><strong>Name: </strong>{{ user.first_name }} {{ user.last_name }}</p>
    {% else %}
        <p><strong>Name: </strong>{{ user.username }}</p>
    {% endif %}
    <p><strong>About Me: </strong></p>
    <p>{{ user.profile.about_me|linebreaksbr }}</p>
    <p><strong>Contact details: </strong></p>
    <p>{{ user.profile.contact_details|linebreaksbr }}</p>
    <p><strong>Prefered Bug Bounty: </strong></p>
    <p>{{ user.profile.prefered_bug_bounty|linebreaksbr }}</p>


    <h4>TODOs</h4>
    <ul>
        <li>show awards</li>
        <li>show reported bugs list</li>
    </ul>

{% endblock content %}

accounts/templates/accounts/pages/settings.html
{% extends 'content_container.html' %}

{% block title %}Settings - {% endblock title %}

{% block content %}
    <h3 class="text-center">Settings</h3>
    <hr />
    <form method="post">
        {% csrf_token %}
        {% include 'form.html' %}
        <button class="float-right btn btn-primary pl-5 pr-5">Save</button>
    </form>
{% endblock content %}

accounts/templates/accounts/pages/signup.html
{% extends 'base.html' %}

{% block title %}Signup -{% endblock title %}


{% block content %}
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="card w-100">
                <div class="card card-header"><h3 class="text-center">Signup</h3></div>
                <div class="card card-body">
                    {% if REGISTRATION_ENABLED %}
                        <form method="POST">
                            {% csrf_token %}
                            {% include "form.html" %}
                            <button class="btn-primary btn text-center w-100">Signup</button>
                        </form>
                    {% else %}
                        <div class="alert alert-info">Registration currently disabled!</div>
                    {% endif %}
                </div>
                <div class="card card-footer">
                    <small>or <a href="{% url 'accounts:login_view' %}">Login</a></small>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}