api/urls.py
from django.urls import path, include
from django.conf import settings
from api import views

app_name = "api"

urlpatterns = [
    path('accounts/', include('accounts.api.urls')),
    path('pentesting/', include('pentesting.urls')),
    path('status/check', views.CheckStatus.as_view(), name='check-status'),
    path('public/', include('public.api.urls')),
]

if settings.ENABLE_BUGHUNTING_APPLICATION:
    urlpatterns += [
        path('bughunting/', include('bughunting.api.urls')),
    ]

if settings.ENABLE_BLOGGING_APPLICATION:
    urlpatterns += [
        path('blogs/', include('blogging.urls'))
    ]

bughunting/api/urls.py
from django.urls import path
from django.conf import settings
from rest_framework.routers import DefaultRouter
from bughunting.api import views

app_name = 'bughunting'

router = DefaultRouter()
router.register(r'user-bugs', views.UserBugViewSet, basename='user-bug')
router.register(r'bugs', views.BugsViewSet, basename='bug')

urlpatterns = [
    path('bugs/<str:pk>/disclosure-deadline', views.IncreaseDisclosureTime.as_view(), name='increase-disclosure-deadline'),
]

urlpatterns += router.urls

bughunting/urls.py
from django.urls import path, include
from bughunting import views


app_name = "bughunting"


urlpatterns = [
    path('bugs/', views.AllBugs.as_view(), name="all_bugs"),
    path('bugs/my/', views.MyBugs.as_view(), name="my-bugs"),
    path('bugs/submit/', views.SubmitBug.as_view(), name='submit-bug'),
    path('bugs/approval/', views.ApproveBugsList.as_view(), name='bugs-approval-list'),
    path('bugs/<str:pk>/', views.SingleBug.as_view(), name="single-bug"),
    path('bugs/<str:pk>/comments/new/', views.WriteBugComment.as_view(), name="write-comment"),
    path('bugs/<str:pk>/edit/', views.UpdateBug.as_view(), name='edit-bug'),
    path('bugs/<str:pk>/approve/', views.BugApproved.as_view(), name='approve-bug'),
    path('bugs/<str:pk>/increase-date-disclosure/',
         views.IncreaseBugDateDisclosure.as_view(), name='increase-date-disclosure'),
    path('bugs/<str:pk>/resend-notification-mail/', views.ResendNotificationMail.as_view(),
         name='resend-notification-mail'),

    path('bugs/token-authentication/', include('bughunting.domain_owner.urls')),
]

opas_f_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework.permissions import IsAuthenticated
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Open Pentesting and Security Framework API",
        default_version="v1",
        description="API of the Open Pentesting and Security Framework",
        contact=openapi.Contact(email=settings.DEFAULT_FROM_EMAIL),
        license=openapi.License(name="GPLv3")
    ),
    public=False,
    permission_classes=(IsAuthenticated,),
)


urlpatterns = [
    path('api/', include('api.urls')),
    path('api-docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('accounts/', include('accounts.urls')),
    path('bughunting/', include('bughunting.urls')),
    path('', include('public.urls')),
    path('master-slave/', include('master_slave.urls'))
]


if settings.ENABLE_ADMIN_INTERFACE:
    urlpatterns += [
        path(settings.ADMIN_URL_PATH, admin.site.urls),
    ]

bughunting/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import uuid
from pinax.badges.registry import badges
from bughunting import badges as my_badges
# Create your models here.


class Bug(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, primary_key=True)
    name = models.CharField(max_length=128)
    domain = models.URLField()
    path = models.CharField(max_length=1024)
    parameter = models.CharField(max_length=64)
    proof_of_concept = models.TextField()
    method = models.CharField(max_length=8, default="GET")
    description = models.TextField(blank=True, null=True)

    @property
    def owner(self):
        return self.bugmeta.user

    def __str__(self):
        return "%s on %s" % (self.name, self.domain)

    def get_absolute_url(self):
        return reverse('bughunting:single-bug', kwargs={'pk': self.pk})

    class Meta:
        unique_together = (('domain', 'parameter', 'path', 'name'),)


class BugMeta(models.Model):
    bug = models.OneToOneField(Bug, on_delete=models.CASCADE, primary_key=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_fixed = models.BooleanField(default=False)
    date_fixed = models.DateField(blank=True, null=True)
    date_discovered = models.DateTimeField(auto_now_add=True)
    is_disclosed = models.BooleanField(default=False)
    date_disclosure = models.DateField(blank=True, null=True, help_text="date when bug becomes auto disclosed")
    date_disclosed = models.DateField(blank=True, null=True)
    approved = models.BooleanField(default=False)
    contact_email = models.EmailField()
    is_sent = models.BooleanField(default=False)
    is_draft = models.BooleanField(default=False)
    date_sent = models.DateTimeField(blank=True, null=True)
    send_email_copy_user = models.BooleanField(default=False)


class Comment(models.Model):
    bug = models.ForeignKey(Bug, on_delete=models.CASCADE)
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)


# Register Badges here
badges.register(my_badges.SecuredWebsitesBadge)
badges.register(my_badges.PatchedBadge)

bughunting/api/views.py
from rest_framework import generics, viewsets, mixins
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import status
from pinax.badges.registry import badges
from bughunting.api import serializers
from bughunting import models
from bughunting.utils.mail.sending import send_vulnerability_mail
from opas_f_server.permissions import IsOwner


class UserBugViewSet(mixins.ListModelMixin, mixins.RetrieveModelMixin,
                     mixins.CreateModelMixin, viewsets.GenericViewSet):
    """ create a new bug, list or update users bug """
    permission_classes = [IsOwner]

    def get_serializer_class(self):
        if self.action == "resend_notification_mail":
            return None
        return serializers.FullBugSerializer

    def perform_create(self, serializer):
        obj = serializer.save()
        if obj.bugmeta.approved:
            badges.possibly_award_badge("secured_websites_awarded", user=self.request.user)
            send_vulnerability_mail(self.request, obj)

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__user=self.request.user)

    @action(methods=['post'], detail=True, permission_classes=[IsOwner], url_path="resend-notification-mail")
    def resend_notification_mail(self, request, pk=None):
        obj = self.get_object()
        data = {'success': False}
        if not obj.bugmeta.is_disclosed:
            send_vulnerability_mail(self.request, obj)
            data['success'] = True
        return Response(data, status=status.HTTP_200_OK)


class BugsViewSet(mixins.ListModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    """ list or retrieve bug. show different information on disclosure state """
    serializer_class = serializers.BaseBugSerializer

    def get_serializer_class(self):
        if self.action == "list":
            return serializers.BaseBugSerializer
        instance = self.get_object()
        if instance.bugmeta.is_disclosed or self.request.user == instance.bugmeta.user:
            return serializers.FullBugSerializer
        return serializers.BaseBugSerializer

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__is_sent=True).order_by(
            '-bugmeta__date_discovered')


class IncreaseDisclosureTime(generics.UpdateAPIView):
    """ increase disclosure deadline of a bug owned by the user"""
    serializer_class = serializers.IncreaseDisclosureTimeSerializer
    permission_classes = [IsOwner]

    def get_queryset(self):
        return models.Bug.objects.filter(pk=self.kwargs.get('pk'), bugmeta__is_disclosed=False)

bughunting/domain_owner/views.py
from django.views import generic
from django.urls import reverse_lazy
from bughunting.forms import WriteCommentForm
from bughunting.utils.tokens.token import validate_access_token


class WriteBugCommentAccessToken(generic.CreateView):
    form_class = WriteCommentForm
    http_method_names = ["post"]

    def get_queryset(self):
        is_domain_owner, queryset = validate_access_token(self.kwargs.get('pk'), self.kwargs.get('token'))
        return queryset

    def get_success_url(self):
        return reverse_lazy('bughunting:domain-owner:bug-details', kwargs={'pk': self.kwargs.get('pk'),
                                                                           'token': self.kwargs.get('token')})

    def form_valid(self, form):
        form.instance.bug = self.get_object()
        return super(WriteBugCommentAccessToken, self).form_valid(form)


class OwnerBugDetails(generic.DetailView):
    template_name = 'bughunting/pages/single_bug_page.html'
    context_object_name = "bug"

    def get_context_data(self, **kwargs):
        is_domain_owner, queryset = validate_access_token(self.kwargs.get('pk'), self.kwargs.get('token'))
        context = super(OwnerBugDetails, self).get_context_data(**kwargs)
        context.update({
            'is_domain_owner': is_domain_owner, 'token': self.kwargs.get('token'),
            'write_comment_form': WriteCommentForm()
        })
        return context

    def get_queryset(self):
        is_domain_owner, queryset = validate_access_token(self.kwargs.get('pk'), self.kwargs.get('token'))
        if queryset:
            queryset = queryset.filter(bugmeta__approved=True)
        return queryset

bughunting/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.db.models import Q
from django.utils import timezone
from pinax.badges.registry import badges
from bughunting import models
from bughunting import forms
from bughunting.utils.mail.sending import send_vulnerability_mail
from opas_f_server.mixins.messages import MessageMixin


class AllBugs(generic.ListView):
    """ show all approved bugs """
    template_name = 'bughunting/pages/all_bugs_page.html'
    paginate_by = 20
    context_object_name = "bugs"
    queryset = models.Bug.objects.filter(bugmeta__approved=True).order_by('-bugmeta__date_discovered')


class SingleBug(generic.DetailView):
    template_name = 'bughunting/pages/single_bug_page.html'
    context_object_name = "bug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.UpdateBugForm()
        context['increase_date_disclosure_form'] = forms.IncreaseBugDateDisclosureForm
        if self.request.user.is_staff:
            context['approve_bug_form'] = forms.ApproveBugForm()
        if self.request.user == self.get_object().bugmeta.user:
            context['write_comment_form'] = forms.WriteCommentForm()
        return context

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return models.Bug.objects.filter(bugmeta__approved=True, pk=self.kwargs.get('pk'), bugmeta__is_draft=False)
        return models.Bug.objects.filter(Q(bugmeta__approved=True, bugmeta__is_draft=False) | Q(
            bugmeta__user=self.request.user), pk=self.kwargs.get('pk'))


class MyBugs(LoginRequiredMixin, generic.ListView):
    template_name = "bughunting/pages/all_bugs_page.html"
    paginate_by = 20
    context_object_name = "bugs"

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__user=self.request.user).order_by('-bugmeta__date_discovered')


class SubmitBug(LoginRequiredMixin, MessageMixin, generic.CreateView):
    form_class = forms.CreateBugForm
    template_name = "bughunting/pages/submit_bug_page.html"
    success_message = "Thanks for submitting this bug!"

    def form_valid(self, form):
        form.instance.user = self.request.user
        instance = form.save()
        bug_meta = models.BugMeta.objects.create(bug=instance,
                                                 send_email_copy_user=form.cleaned_data['send_email_copy_user'],
                                                 is_fixed=form.cleaned_data['is_fixed'], user=self.request.user,
                                                 contact_email=form.cleaned_data['contact_email'],
                                                 is_draft=form.cleaned_data['is_draft'])
        if not settings.BUGHUNTING_NEED_MANUAL_APPROVING and not bug_meta.is_draft:
            bug_meta.approved = True
            bug_meta.save()
            badges.possibly_award_badge("secured_websites_awarded", user=self.request.user)
            send_vulnerability_mail(self.request, instance)
        return super(SubmitBug, self).form_valid(form)


class ApproveBugsList(LoginRequiredMixin, generic.ListView):
    template_name = "bughunting/pages/approve_bugs_page.html"
    paginate_by = 20
    context_object_name = "bugs"

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__approved=False, bugmeta__is_draft=False)


class UpdateBug(LoginRequiredMixin, MessageMixin, generic.UpdateView):
    form_class = forms.UpdateBugForm
    success_message = "Updated bug successfully!"

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__user=self.request.user, pk=self.kwargs.get('pk'))

    def form_valid(self, form):
        obj = self.get_object()
        if not obj.bugmeta.is_disclosed:
            date = timezone.now().date()
            if not obj.bugmeta.is_draft:
                form.cleaned_data['is_draft'] = False
            self.handle_drafts(obj, form.cleaned_data)
            if form.cleaned_data.get('is_fixed', False):
                obj.bugmeta.date_fixed = date
                obj.bugmeta.is_fixed = True
                obj.bugmeta.is_disclosed = True
                obj.bugmeta.date_disclosed = date
            obj.bugmeta.is_draft = form.cleaned_data.get('is_draft')
            obj.bugmeta.save()
            if obj.bugmeta.is_fixed:
                badges.possibly_award_badge('patched_websites_awarded', user=self.request.user)
        return super(UpdateBug, self).form_valid(form)

    def handle_drafts(self, instance, cleaned_data):
        if instance.bugmeta.is_draft is True and not cleaned_data.get('is_draft'):
            if cleaned_data['is_draft'] is True:
                return
            if not settings.BUGHUNTING_NEED_MANUAL_APPROVING and not instance.bugmeta.is_draft:
                instance.bugmeta.approved = True
                instance.bugmeta.save()
                badges.possibly_award_badge("secured_websites_awarded", user=self.request.user)
                send_vulnerability_mail(self.request, instance)


class BugApproved(LoginRequiredMixin, MessageMixin, generic.UpdateView):
    form_class = forms.ApproveBugForm
    success_message = "Bug approved!"

    def get_queryset(self):
        if self.request.user.is_staff:
            return models.Bug.objects.filter(bugmeta__approved=False, pk=self.kwargs.get('pk'), bugmeta__is_draft=False)
        return models.Bug.objects.none()

    def form_valid(self, form):
        obj = self.get_object()
        obj.bugmeta.approved = form.cleaned_data['approved']
        obj.bugmeta.save()
        if obj.bugmeta.approved:
            send_vulnerability_mail(self.request, obj)
        return super(BugApproved, self).form_valid(form)


class IncreaseBugDateDisclosure(LoginRequiredMixin, generic.UpdateView):
    form_class = forms.IncreaseBugDateDisclosureForm
    http_method_names = ["post"]

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__approved=True, pk=self.kwargs.get('pk'),
                                         bugmeta__is_draft=False, bugmeta__user=self.request.user)

    def form_valid(self, form):
        obj = self.get_object()
        date = obj.bugmeta.date_disclosure + timezone.timedelta(
            days=form.cleaned_data.get('days'))
        obj.bugmeta.date_disclosure = date
        obj.bugmeta.save()
        obj.save()
        return super(IncreaseBugDateDisclosure, self).form_valid(form)


class ResendNotificationMail(LoginRequiredMixin, generic.UpdateView):
    form_class = forms.ResendNotificationMailForm
    http_method_names = ["post"]

    def get_queryset(self):
        return models.Bug.objects.filter(pk=self.kwargs.get('pk'), bugmeta__approved=True, bugmeta__is_disclosed=False)

    def form_valid(self, form):
        instance = form.instance
        send_vulnerability_mail(self.request, instance)
        return super(ResendNotificationMail, self).form_valid(form)


class WriteBugComment(LoginRequiredMixin, generic.CreateView):
    form_class = forms.WriteCommentForm
    http_method_names = ["post"]

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__user=self.request.user, pk=self.kwargs.get('pk'))

    def get_success_url(self):
        return self.get_object().get_absolute_url()

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.bug = self.get_object()
        return super(WriteBugComment, self).form_valid(form)

bughunting/templates/bughunting/pages/all_bugs_page.html
{% extends 'content_container.html' %}

{% block title %}Bugs -{% endblock title %}

{% block content %}
    <h3 class="text-center">Reported Bugs</h3>
    <hr />
    <div class="list-group">
        {% for bug in bugs %}
            {% include 'bughunting/components/bug_list_item.html' with bug=bug %}
        {% empty %}
            <div class="alert alert-info">No bug found!</div>
        {% endfor %}
    </div>
    {% include 'navigation/paginator.html' %}
{% endblock content %}

bughunting/templates/bughunting/pages/approve_bugs_page.html
{% extends 'content_container.html' %}

{% block title %}Bugs -{% endblock title %}

{% block content %}
    <h3 class="text-center">Bugs needing approval</h3>
    <hr />
    <div class="list-group">
        {% for bug in bugs %}
            {% include 'bughunting/components/bug_list_item.html' with bug=bug %}
        {% empty %}
            <div class="alert alert-info">No bugs found!</div>
        {% endfor %}
    </div>
    {% include 'navigation/paginator.html' %}
{% endblock content %}

bughunting/templates/bughunting/pages/single_bug_page.html
{% extends 'content_container.html' %}

{% block title %}{{ bug.name }} - {% endblock title %}


{% block content %}
    <div class="float-right">
        {% include 'bughunting/components/bug_status_badge.html' %}
    </div>
    <h3 class="text-center">{{ bug }}</h3>
    <hr />
    <div class="card card-body">
        {% if bug.bugmeta.user == request.user and not bug.bugmeta.is_fixed %}
            <div class="float-right">
                <button class="btn btn-outline-info float-right" type="button" data-toggle="modal" data-target="#edit_bug_modal">
                    <i class="fa fa-edit"></i> Edit
                </button>
            </div>
            {% if not bug.bugmeta.is_disclosed %}
                <div class="float-right">
                    <button class="btn btn-outline-secondary float-right" type="button" data-toggle="modal" data-target="#increase_bug_date_disclosure_modal">
                        <i class="fa fa-chart-line"></i> Increase date disclosure
                    </button>
                </div>
            {% endif %}
        {% elif is_domain_owner %}
            <div class="float-right">
                <button class="btn btn-outline-info">Mark as fixed</button>
            </div>
        {% endif %}
        {% if request.user.is_staff and not bug.bugmeta.is_draft and not bug.bugmeta.approved %}
            <div class="float-right">
                <button class="btn btn-outline-primary float-right" type="button" data-toggle="modal" data-target="#approve_bug_modal">
                    <i class="fa fa-check"></i> Approve
                </button>
            </div>
        {% endif %}
        <p><strong>Domain: </strong>{{ bug.domain }}</p>
        <p><strong>Name: </strong>{{ bug.name }}</p>
        <p><strong>Submitted: </strong>{{ bug.bugmeta.date_discovered }}</p>
        <p><strong>Bug-Hunter: </strong>{{ bug.bugmeta.user }}</p>
        {% if bug.bugmeta.is_disclosed or request.user == bug.bugmeta.user or is_domain_owner %}
            {% if bug.bugmeta.is_disclosed %}
                <p><strong>Date disclosed: </strong>{{ bug.bugmeta.date_disclosed }}</p>
            {% else %}
                <p><strong>Date disclosure: </strong>{{ bug.bugmeta.date_disclosure }}</p>
            {% endif %}
            <p><strong>Parameter: </strong>{{ bug.parameter }}</p>
            <p><strong>Path: </strong>{{ bug.path }}</p>
            <p><strong>Proof-of-concept: </strong>{{ bug.proof_of_concept | linebreaksbr }}</p>
        {% else %}
            <p><strong>Date disclosure: </strong>{{ bug.bugmeta.date_disclosure }}</p>
            <div class="alert alert-info">Details hidden until disclosure!</div>
        {% endif %}
    </div>

    {% include 'bughunting/components/edit_bug_modal.html' %}
    {% include 'bughunting/components/increase_bug_date_disclosure_modal.html' with form=increase_date_disclosure_form %}
    {% if request.user.is_staff %}
        {% include 'bughunting/components/approve_bug_modal.html' with form=approve_bug_form %}
    {% endif %}

    {% if bug.bugmeta.is_disclosed or request.user == bug.bugmeta.user or is_domain_owner %}
        <div class="mt-5">
            <h4>Comments: </h4>
            {% include 'bughunting/components/bug_comments_list.html' with comments=bug.comment_set.all %}
        </div>
    {% endif %}

    {% if write_comment_form %}
        <div class="mt-5">
            {% include 'bughunting/components/write_comment_form.html' with form=write_comment_form %}
        </div>
    {% endif %}
{% endblock content %}

bughunting/templates/bughunting/pages/submit_bug_page.html
{% extends 'content_container.html' %}


{% block title %}{% endblock title %}


{% block content %}
    <h3 class="text-center">Submit bug</h3>
    <hr />
    <form method="post">
        {% csrf_token %}
        {% include 'form.html' %}
        <button class="btn btn-info float-right pl-5 pr-5">Submit</button>
    </form>
{% endblock content %}