accounts/urls.py
from django.urls import path, include
from accounts import views


app_name = "accounts"


urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login_view"),
    path('signup/', views.SignupView.as_view(), name='signup_view'),
    path('activate/<str:uidb64>/<str:token>/', views.ActivateAccount.as_view(), name='activate-account'),
    path('logout/', views.LogoutView.as_view(), name="logout_view"),
    path('dashboard/', include('accounts.dashboard.urls')),
    path('settings/', views.UpdateSettings.as_view(), name='settings'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit-profile'),
]

api/urls.py
from django.urls import path, include
from django.conf import settings
from api import views

app_name = "api"

urlpatterns = [
    path('accounts/', include('accounts.api.urls')),
    path('pentesting/', include('pentesting.urls')),
    path('status/check', views.CheckStatus.as_view(), name='check-status'),
    path('public/', include('public.api.urls')),
]

if settings.ENABLE_BUGHUNTING_APPLICATION:
    urlpatterns += [
        path('bughunting/', include('bughunting.api.urls')),
    ]

if settings.ENABLE_BLOGGING_APPLICATION:
    urlpatterns += [
        path('blogs/', include('blogging.urls'))
    ]

bughunting/urls.py
from django.urls import path, include
from bughunting import views


app_name = "bughunting"


urlpatterns = [
    path('bugs/', views.AllBugs.as_view(), name="all_bugs"),
    path('bugs/my/', views.MyBugs.as_view(), name="my-bugs"),
    path('bugs/submit/', views.SubmitBug.as_view(), name='submit-bug'),
    path('bugs/approval/', views.ApproveBugsList.as_view(), name='bugs-approval-list'),
    path('bugs/<str:pk>/', views.SingleBug.as_view(), name="single-bug"),
    path('bugs/<str:pk>/comments/new/', views.WriteBugComment.as_view(), name="write-comment"),
    path('bugs/<str:pk>/edit/', views.UpdateBug.as_view(), name='edit-bug'),
    path('bugs/<str:pk>/approve/', views.BugApproved.as_view(), name='approve-bug'),
    path('bugs/<str:pk>/increase-date-disclosure/',
         views.IncreaseBugDateDisclosure.as_view(), name='increase-date-disclosure'),
    path('bugs/<str:pk>/resend-notification-mail/', views.ResendNotificationMail.as_view(),
         name='resend-notification-mail'),

    path('bugs/token-authentication/', include('bughunting.domain_owner.urls')),
]

master_slave/urls.py
from django.urls import path
from master_slave import views

app_name = "master-slave"


urlpatterns = [
    path('new/', views.CreateSlave.as_view(), name='create-slave'),
    path('', views.ListSlaves.as_view(), name='index'),
    path('<int:pk>/', views.SingleSlave.as_view(), name='single-slave'),
    path('<int:pk>/delete/', views.DeleteSlave.as_view(), name='delete-slave'),
]

opas_f_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework.permissions import IsAuthenticated
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Open Pentesting and Security Framework API",
        default_version="v1",
        description="API of the Open Pentesting and Security Framework",
        contact=openapi.Contact(email=settings.DEFAULT_FROM_EMAIL),
        license=openapi.License(name="GPLv3")
    ),
    public=False,
    permission_classes=(IsAuthenticated,),
)


urlpatterns = [
    path('api/', include('api.urls')),
    path('api-docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('accounts/', include('accounts.urls')),
    path('bughunting/', include('bughunting.urls')),
    path('', include('public.urls')),
    path('master-slave/', include('master_slave.urls'))
]


if settings.ENABLE_ADMIN_INTERFACE:
    urlpatterns += [
        path(settings.ADMIN_URL_PATH, admin.site.urls),
    ]

templates/navigation/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'public:index-page' %}">Open Pentesting and Security Framework</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="basicExampleNav">

    <ul class="nav navbar-nav nav-flex-icons mr-auto text-light">
      <li class="nav-item">
        {% if request.user.is_authenticated %}
          <a class="nav-link" href="{% url 'accounts:dashboard:index' %}">Dashboard
            <span class="sr-only">(current)</span>
          </a>
        {% else %}
          <a class="nav-link" href="{% url 'public:index-page' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        {% endif %}
      </li>


      {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="#"> My Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'master-slave:index' %}">Master-Slave</a>
          </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="bug_hunting_dropdown" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Bug-Hunting</a>
        <div class="dropdown-menu" aria-labelledby="bug_hunting_dropdown">
          <a class="dropdown-item" href="{% url 'bughunting:all_bugs' %}">All Bugs</a>
          <a class="dropdown-item" href="{% url 'bughunting:my-bugs' %}">My Bugs</a>
          <a class="dropdown-item" href="{% url 'bughunting:submit-bug' %}">Submit Bug</a>
          {% if request.user.is_authenticated and request.user.is_staff %}
                <a class="dropdown-item" href="{% url 'bughunting:bugs-approval-list' %}">Approve bugs</a>
          {% endif %}
        </div>
      </li>

        {% if request.user.is_authenticated and request.user.blog %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="blogging_dropdown" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Blogging</a>
                <div class="dropdown-menu" aria-labelledby="blogging_dropdown">
                    <a class="dropdown-item" href="#">New Post</a>
                    <a class="dropdown-item" href="#">View my blog</a>
                </div>
            </li>
        {% endif %}
    </ul>

    <ul class="nav navbar-nav nav-flex-icons ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="javascript:alert('not implemented')">
          <i class="fa fa-envelope"></i> <span class="clearfix d-none d-sm-inline-block">Contact</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://codeberg.org/OPAS-F/opas-f-server/issues" target="_blank">
          <i class="fa fa-comments-o"></i> <span class="clearfix d-none d-sm-inline-block">Support</span>
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="user_menu_dropdown" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-user"></i>
            {{request.user.username}}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user_menu_dropdown">
            <a class="dropdown-item" href="{% url 'accounts:profile' request.user.pk %}">Profile</a>
            <a class="dropdown-item" href="{% url 'accounts:settings' %}">Settings</a>
            <a class="dropdown-item" href="{% url 'accounts:logout_view' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login_view' %}">
            <i class="fa fa-lock"></i> <span class="clearfix d-none d-sm-inline-block">Login</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/navigation/paginator.html
{% if is_paginated %}
    <ul class="pagination justify-content-center" style="margin:20px 0">
        {% if page_obj.has_previous %}
            <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">Previous</a></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
            {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">Next</a></li>
        {% endif %}
    </ul>
{% endif %}