api/urls.py
from django.urls import path, include
from django.conf import settings
from api import views

app_name = "api"

urlpatterns = [
    path('accounts/', include('accounts.api.urls')),
    path('pentesting/', include('pentesting.urls')),
    path('status/check', views.CheckStatus.as_view(), name='check-status'),
    path('public/', include('public.api.urls')),
]

if settings.ENABLE_BUGHUNTING_APPLICATION:
    urlpatterns += [
        path('bughunting/', include('bughunting.api.urls')),
    ]

if settings.ENABLE_BLOGGING_APPLICATION:
    urlpatterns += [
        path('blogs/', include('blogging.urls'))
    ]

bughunting/api/urls.py
from django.urls import path
from django.conf import settings
from rest_framework.routers import DefaultRouter
from bughunting.api import views

app_name = 'bughunting'

router = DefaultRouter()
router.register(r'user-bugs', views.UserBugViewSet, basename='user-bug')
router.register(r'bugs', views.BugsViewSet, basename='bug')

urlpatterns = [
    path('bugs/<str:pk>/disclosure-deadline', views.IncreaseDisclosureTime.as_view(), name='increase-disclosure-deadline'),
]

urlpatterns += router.urls

bughunting/urls.py
from django.urls import path, include
from bughunting import views


app_name = "bughunting"


urlpatterns = [
    path('bugs/', views.AllBugs.as_view(), name="all_bugs"),
    path('bugs/my/', views.MyBugs.as_view(), name="my-bugs"),
    path('bugs/submit/', views.SubmitBug.as_view(), name='submit-bug'),
    path('bugs/approval/', views.ApproveBugsList.as_view(), name='bugs-approval-list'),
    path('bugs/<str:pk>/', views.SingleBug.as_view(), name="single-bug"),
    path('bugs/<str:pk>/comments/new/', views.WriteBugComment.as_view(), name="write-comment"),
    path('bugs/<str:pk>/edit/', views.UpdateBug.as_view(), name='edit-bug'),
    path('bugs/<str:pk>/approve/', views.BugApproved.as_view(), name='approve-bug'),
    path('bugs/<str:pk>/increase-date-disclosure/',
         views.IncreaseBugDateDisclosure.as_view(), name='increase-date-disclosure'),
    path('bugs/<str:pk>/resend-notification-mail/', views.ResendNotificationMail.as_view(),
         name='resend-notification-mail'),

    path('bugs/token-authentication/', include('bughunting.domain_owner.urls')),
]

opas_f_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework.permissions import IsAuthenticated
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Open Pentesting and Security Framework API",
        default_version="v1",
        description="API of the Open Pentesting and Security Framework",
        contact=openapi.Contact(email=settings.DEFAULT_FROM_EMAIL),
        license=openapi.License(name="GPLv3")
    ),
    public=False,
    permission_classes=(IsAuthenticated,),
)


urlpatterns = [
    path('api/', include('api.urls')),
    path('api-docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('accounts/', include('accounts.urls')),
    path('bughunting/', include('bughunting.urls')),
    path('', include('public.urls')),
    path('master-slave/', include('master_slave.urls'))
]


if settings.ENABLE_ADMIN_INTERFACE:
    urlpatterns += [
        path(settings.ADMIN_URL_PATH, admin.site.urls),
    ]

bughunting/forms.py
from django import forms
from bughunting import models


class CreateBugForm(forms.ModelForm):
    contact_email = forms.EmailField()
    is_fixed = forms.BooleanField(required=False)
    is_draft = forms.BooleanField(required=False)
    send_email_copy_user = forms.BooleanField(required=False)

    class Meta:
        model = models.Bug
        exclude = ('uuid', )


class UpdateBugForm(forms.ModelForm):
    is_fixed = forms.BooleanField(required=False)
    is_draft = forms.BooleanField(required=False)

    class Meta:
        model = models.Bug
        fields = ['is_fixed', 'is_draft']


class ApproveBugForm(forms.ModelForm):
    approved = forms.BooleanField()

    class Meta:
        model = models.Bug
        fields = ['approved']


class IncreaseBugDateDisclosureForm(forms.ModelForm):
    days = forms.IntegerField(min_value=1, max_value=90)

    class Meta:
        model = models.Bug
        fields = ['days']


class WriteCommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['text']


class ResendNotificationMailForm(forms.ModelForm):
    class Meta:
        model = models.Bug
        fields = []

bughunting/api/views.py
from rest_framework import generics, viewsets, mixins
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import status
from pinax.badges.registry import badges
from bughunting.api import serializers
from bughunting import models
from bughunting.utils.mail.sending import send_vulnerability_mail
from opas_f_server.permissions import IsOwner


class UserBugViewSet(mixins.ListModelMixin, mixins.RetrieveModelMixin,
                     mixins.CreateModelMixin, viewsets.GenericViewSet):
    """ create a new bug, list or update users bug """
    permission_classes = [IsOwner]

    def get_serializer_class(self):
        if self.action == "resend_notification_mail":
            return None
        return serializers.FullBugSerializer

    def perform_create(self, serializer):
        obj = serializer.save()
        if obj.bugmeta.approved:
            badges.possibly_award_badge("secured_websites_awarded", user=self.request.user)
            send_vulnerability_mail(self.request, obj)

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__user=self.request.user)

    @action(methods=['post'], detail=True, permission_classes=[IsOwner], url_path="resend-notification-mail")
    def resend_notification_mail(self, request, pk=None):
        obj = self.get_object()
        data = {'success': False}
        if not obj.bugmeta.is_disclosed:
            send_vulnerability_mail(self.request, obj)
            data['success'] = True
        return Response(data, status=status.HTTP_200_OK)


class BugsViewSet(mixins.ListModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    """ list or retrieve bug. show different information on disclosure state """
    serializer_class = serializers.BaseBugSerializer

    def get_serializer_class(self):
        if self.action == "list":
            return serializers.BaseBugSerializer
        instance = self.get_object()
        if instance.bugmeta.is_disclosed or self.request.user == instance.bugmeta.user:
            return serializers.FullBugSerializer
        return serializers.BaseBugSerializer

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__is_sent=True).order_by(
            '-bugmeta__date_discovered')


class IncreaseDisclosureTime(generics.UpdateAPIView):
    """ increase disclosure deadline of a bug owned by the user"""
    serializer_class = serializers.IncreaseDisclosureTimeSerializer
    permission_classes = [IsOwner]

    def get_queryset(self):
        return models.Bug.objects.filter(pk=self.kwargs.get('pk'), bugmeta__is_disclosed=False)

bughunting/domain_owner/views.py
from django.views import generic
from django.urls import reverse_lazy
from bughunting.forms import WriteCommentForm
from bughunting.utils.tokens.token import validate_access_token


class WriteBugCommentAccessToken(generic.CreateView):
    form_class = WriteCommentForm
    http_method_names = ["post"]

    def get_queryset(self):
        is_domain_owner, queryset = validate_access_token(self.kwargs.get('pk'), self.kwargs.get('token'))
        return queryset

    def get_success_url(self):
        return reverse_lazy('bughunting:domain-owner:bug-details', kwargs={'pk': self.kwargs.get('pk'),
                                                                           'token': self.kwargs.get('token')})

    def form_valid(self, form):
        form.instance.bug = self.get_object()
        return super(WriteBugCommentAccessToken, self).form_valid(form)


class OwnerBugDetails(generic.DetailView):
    template_name = 'bughunting/pages/single_bug_page.html'
    context_object_name = "bug"

    def get_context_data(self, **kwargs):
        is_domain_owner, queryset = validate_access_token(self.kwargs.get('pk'), self.kwargs.get('token'))
        context = super(OwnerBugDetails, self).get_context_data(**kwargs)
        context.update({
            'is_domain_owner': is_domain_owner, 'token': self.kwargs.get('token'),
            'write_comment_form': WriteCommentForm()
        })
        return context

    def get_queryset(self):
        is_domain_owner, queryset = validate_access_token(self.kwargs.get('pk'), self.kwargs.get('token'))
        if queryset:
            queryset = queryset.filter(bugmeta__approved=True)
        return queryset

bughunting/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.db.models import Q
from django.utils import timezone
from pinax.badges.registry import badges
from bughunting import models
from bughunting import forms
from bughunting.utils.mail.sending import send_vulnerability_mail
from opas_f_server.mixins.messages import MessageMixin


class AllBugs(generic.ListView):
    """ show all approved bugs """
    template_name = 'bughunting/pages/all_bugs_page.html'
    paginate_by = 20
    context_object_name = "bugs"
    queryset = models.Bug.objects.filter(bugmeta__approved=True).order_by('-bugmeta__date_discovered')


class SingleBug(generic.DetailView):
    template_name = 'bughunting/pages/single_bug_page.html'
    context_object_name = "bug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.UpdateBugForm()
        context['increase_date_disclosure_form'] = forms.IncreaseBugDateDisclosureForm
        if self.request.user.is_staff:
            context['approve_bug_form'] = forms.ApproveBugForm()
        if self.request.user == self.get_object().bugmeta.user:
            context['write_comment_form'] = forms.WriteCommentForm()
        return context

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return models.Bug.objects.filter(bugmeta__approved=True, pk=self.kwargs.get('pk'), bugmeta__is_draft=False)
        return models.Bug.objects.filter(Q(bugmeta__approved=True, bugmeta__is_draft=False) | Q(
            bugmeta__user=self.request.user), pk=self.kwargs.get('pk'))


class MyBugs(LoginRequiredMixin, generic.ListView):
    template_name = "bughunting/pages/all_bugs_page.html"
    paginate_by = 20
    context_object_name = "bugs"

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__user=self.request.user).order_by('-bugmeta__date_discovered')


class SubmitBug(LoginRequiredMixin, MessageMixin, generic.CreateView):
    form_class = forms.CreateBugForm
    template_name = "bughunting/pages/submit_bug_page.html"
    success_message = "Thanks for submitting this bug!"

    def form_valid(self, form):
        form.instance.user = self.request.user
        instance = form.save()
        bug_meta = models.BugMeta.objects.create(bug=instance,
                                                 send_email_copy_user=form.cleaned_data['send_email_copy_user'],
                                                 is_fixed=form.cleaned_data['is_fixed'], user=self.request.user,
                                                 contact_email=form.cleaned_data['contact_email'],
                                                 is_draft=form.cleaned_data['is_draft'])
        if not settings.BUGHUNTING_NEED_MANUAL_APPROVING and not bug_meta.is_draft:
            bug_meta.approved = True
            bug_meta.save()
            badges.possibly_award_badge("secured_websites_awarded", user=self.request.user)
            send_vulnerability_mail(self.request, instance)
        return super(SubmitBug, self).form_valid(form)


class ApproveBugsList(LoginRequiredMixin, generic.ListView):
    template_name = "bughunting/pages/approve_bugs_page.html"
    paginate_by = 20
    context_object_name = "bugs"

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__approved=False, bugmeta__is_draft=False)


class UpdateBug(LoginRequiredMixin, MessageMixin, generic.UpdateView):
    form_class = forms.UpdateBugForm
    success_message = "Updated bug successfully!"

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__user=self.request.user, pk=self.kwargs.get('pk'))

    def form_valid(self, form):
        obj = self.get_object()
        if not obj.bugmeta.is_disclosed:
            date = timezone.now().date()
            if not obj.bugmeta.is_draft:
                form.cleaned_data['is_draft'] = False
            self.handle_drafts(obj, form.cleaned_data)
            if form.cleaned_data.get('is_fixed', False):
                obj.bugmeta.date_fixed = date
                obj.bugmeta.is_fixed = True
                obj.bugmeta.is_disclosed = True
                obj.bugmeta.date_disclosed = date
            obj.bugmeta.is_draft = form.cleaned_data.get('is_draft')
            obj.bugmeta.save()
            if obj.bugmeta.is_fixed:
                badges.possibly_award_badge('patched_websites_awarded', user=self.request.user)
        return super(UpdateBug, self).form_valid(form)

    def handle_drafts(self, instance, cleaned_data):
        if instance.bugmeta.is_draft is True and not cleaned_data.get('is_draft'):
            if cleaned_data['is_draft'] is True:
                return
            if not settings.BUGHUNTING_NEED_MANUAL_APPROVING and not instance.bugmeta.is_draft:
                instance.bugmeta.approved = True
                instance.bugmeta.save()
                badges.possibly_award_badge("secured_websites_awarded", user=self.request.user)
                send_vulnerability_mail(self.request, instance)


class BugApproved(LoginRequiredMixin, MessageMixin, generic.UpdateView):
    form_class = forms.ApproveBugForm
    success_message = "Bug approved!"

    def get_queryset(self):
        if self.request.user.is_staff:
            return models.Bug.objects.filter(bugmeta__approved=False, pk=self.kwargs.get('pk'), bugmeta__is_draft=False)
        return models.Bug.objects.none()

    def form_valid(self, form):
        obj = self.get_object()
        obj.bugmeta.approved = form.cleaned_data['approved']
        obj.bugmeta.save()
        if obj.bugmeta.approved:
            send_vulnerability_mail(self.request, obj)
        return super(BugApproved, self).form_valid(form)


class IncreaseBugDateDisclosure(LoginRequiredMixin, generic.UpdateView):
    form_class = forms.IncreaseBugDateDisclosureForm
    http_method_names = ["post"]

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__approved=True, pk=self.kwargs.get('pk'),
                                         bugmeta__is_draft=False, bugmeta__user=self.request.user)

    def form_valid(self, form):
        obj = self.get_object()
        date = obj.bugmeta.date_disclosure + timezone.timedelta(
            days=form.cleaned_data.get('days'))
        obj.bugmeta.date_disclosure = date
        obj.bugmeta.save()
        obj.save()
        return super(IncreaseBugDateDisclosure, self).form_valid(form)


class ResendNotificationMail(LoginRequiredMixin, generic.UpdateView):
    form_class = forms.ResendNotificationMailForm
    http_method_names = ["post"]

    def get_queryset(self):
        return models.Bug.objects.filter(pk=self.kwargs.get('pk'), bugmeta__approved=True, bugmeta__is_disclosed=False)

    def form_valid(self, form):
        instance = form.instance
        send_vulnerability_mail(self.request, instance)
        return super(ResendNotificationMail, self).form_valid(form)


class WriteBugComment(LoginRequiredMixin, generic.CreateView):
    form_class = forms.WriteCommentForm
    http_method_names = ["post"]

    def get_queryset(self):
        return models.Bug.objects.filter(bugmeta__user=self.request.user, pk=self.kwargs.get('pk'))

    def get_success_url(self):
        return self.get_object().get_absolute_url()

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.bug = self.get_object()
        return super(WriteBugComment, self).form_valid(form)

bughunting/templates/bughunting/components/approve_bug_modal.html
<div class="modal fade" id="approve_bug_modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Approve Bug</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'bughunting:approve-bug' bug.pk %}">
                    {% csrf_token %}
                    {% include 'form.html' %}
                    <button class="btn btn-primary float-right">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>

bughunting/templates/bughunting/components/bug_comments_list.html
<div class="list-group">
    {% for comment in comments %}
        <div class="list-group-item">
            {% if comment.user %}
                <p>{{ comment.user }} - {{ comment.date|timesince }} ago</p>
            {% else %}
                <p>Domain Admin - {{ comment.date|timesince }} ago</p>
            {% endif %}
            <div class="mt-3">
                {{ comment.text }}
            </div>
        </div>
    {% empty %}
        <div class="alert alert-info">No comments yet!</div>
    {% endfor %}
</div>

bughunting/templates/bughunting/components/bug_list_item.html
<a class="list-group-item list-group-item-action" href="{{ bug.get_absolute_url }}">
    <div class="row">
        <div class="col-sm-12">
            <div class="clearfix">
                <div class="float-left">
                    <strong>{{ bug.domain }} ({{ bug.name }})</strong>
                </div>
                <div class="float-right">
                    {% include 'bughunting/components/bug_status_badge.html' with bug=bug %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="clearfix">
                <div class="float-left">
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-sm-12">
            <div class="clearfix">
                <div class="float-left">
                    <small>by {{ bug.bugmeta.user }} on {{ bug.bugmeta.date_discovered }}</small>
                </div>
                <div class="float-right">
                    {% if bug.bugmeta.date_disclosed %}
                        <small>Date disclosed: {{ bug.bugmeta.date_disclosed }}</small>
                    {% else %}
                        <small>Disclosure in {{ bug.bugmeta.date_disclosure | timeuntil }} days</small>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</a>

bughunting/templates/bughunting/components/bug_status_badge.html
{% if not bug.bugmeta.approved and not bug.bugmeta.is_draft %}
    <div class="badge badge-pill badge-info">Not approved</div>
{% elif bug.bugmeta.is_disclosed %}
    {% if bug.bugmeta.is_fixed %}
        <div class="badge badge-pill badge-success">patched</div>
    {% else %}
        <div class="badge badge-pill badge-danger">unpatched</div>
    {% endif %}
{% elif bug.bugmeta.is_draft %}
    <div class="badge badge-pill badge-secondary">draft</div>
{% else %}
    <div class="badge badge-pill badge-info">awaiting response</div>
{% endif %}

bughunting/templates/bughunting/components/edit_bug_modal.html
<div class="modal fade" id="edit_bug_modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Bug</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'bughunting:edit-bug' bug.pk %}">
                    {% csrf_token %}
                    {% include 'form.html' %}
                    <button class="btn btn-primary float-right">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>

bughunting/templates/bughunting/components/increase_bug_date_disclosure_modal.html
<div class="modal fade" id="increase_bug_date_disclosure_modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Increase date disclosure</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'bughunting:increase-date-disclosure' bug.pk %}">
                    {% csrf_token %}
                    {% include 'form.html' %}
                    <button class="btn btn-primary float-right">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>

bughunting/templates/bughunting/components/write_comment_form.html
{% if is_domain_owner %}
    <form class="form" method="POST" action="{% url 'bughunting:domain-owner:write-comment' bug.pk token %}">
        {% csrf_token %}
        {% include 'form.html' %}
        <button class="btn btn-primary pl-5 pr-5 float-right">Save</button>
    </form>
{% else %}
    <form class="form" method="POST" action="{% url 'bughunting:write-comment' bug.pk %}">
        {% csrf_token %}
        {% include 'form.html' %}
        <button class="btn btn-primary pl-5 pr-5 float-right">Save</button>
    </form>
{% endif %}